[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
cp_swap = "8FtgY3WxHTFMJP7AZKhBZHF1KiSDZ6SBbbxLK1wpAcBo"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/impermanent-loss.ts\""

[hooks]
